#!/bin/bash
# Converts all jpeg images in the current directory to a flv video sequence.
# Relies on the mencoder package.
#
# To read the resulting file, use :
# mplayer output.flv


mencoder "mf://*.jpg" -mf fps=12 -o output.flv -ovc lavc -lavcopts vcodec=flv 


