#!/bin/bash
for package in ffmpeg  gettext  gstreamer0.10-ffmpeg  gstreamer0.10-plugins-bad  gstreamer0.10-plugins-base  gstreamer0.10-plugins-good  gstreamer0.10-plugins-ugly   gstreamer0.10-x  help2man  libasound-dev  libavc1394-dev  libboost-program-options-dev  libboost-filesystem-dev  libboost-thread-dev  libboost-date-time-dev  libboost-signals-dev  libboost-system-dev  liblo-dev libclutter-1.0-dev  libclutter-gtk-0.10-dev  libglew1.5-dev  libglib2.0-dev  libglu1-mesa-dev  libgstreamer-plugins-base0.10-dev  libgstreamer0.10-dev  libgtk2.0-dev  libraw1394-dev  libstk0-dev  libxml2-dev  libxv-dev  mencoder automake bison build-essential flex libtool;
do apt-show-versions $package
done
