#!/usr/bin/env python
"""
Interface between Arduino and Toonloop.
"""
import serial
import time

DEVICE_FILE = "/dev/ttyACM0"
BAUD_RATE = 19200

CHAR_ZERO = 48
CHAR_ONE = 49

def run():
    device = serial.Serial(
        port=DEVICE_FILE, 
        baudrate=BAUD_RATE)
    try:
        while True:
            data = device.readline()
            if data.startswith("1"):
                print("yes")
            else:
                print("no")
            time.sleep(0.0001)
    except KeyboardInterrupt, e:
        print("Bye.")

if __name__ == "__main__":
    run()

