#!/usr/bin/env python
"""
Sends /ping to localhost:11337
"""
import liblo
import sys

# send all messages to port 1234 on the local machine
try:
    target = liblo.Address(11337)
except liblo.AddressError, err:
    print str(err)
    sys.exit()

# send message 
liblo.send(target, "/ping")
