#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Toonloop 
#
# Copyright 2010 Alexandre Quessy
# <alexandre@quessy.net>
# http://www.toonloop.com
#
# Toonloop is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Toonloop is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the gnu general public license
# along with Toonloop.  If not, see <http://www.gnu.org/licenses/>.
#
"""
Web server for files.
"""
import os
import sys
from twisted.internet import reactor
from twisted.web import static
from twisted.web import server

__version__ = "0.1.0"

def run(dir_path='.', port=8000): 
    """
    Runs the web server.
    :param port: web server port
    """
    files_path = os.path.expanduser(dir_path)
    if not os.path.isdir(files_path):
        raise RuntimeError("%s must be a directory." % (files_path))
    print("Static files directory is %s" % (files_path))
    root = static.File(files_path)
    site = server.Site(root)
    print("Starting server on port %s." % (port))
    reactor.listenTCP(port, site)

if __name__ == '__main__':
    import optparse
    parser = optparse.OptionParser(usage="%prog", version=__version__) 
    parser.add_option("-p", "--port", type="int", help="Specifies a port to listen on.", default=8080)
    parser.add_option("-d", "--directory", type="string", help="Specifies the directory in which to look for files to serve.", default='.')
    (options, args) = parser.parse_args()
    run(dir_path=options.directory, port=options.port)
    try:
        reactor.run()
    except KeyboardInterrupt:
        pass
